# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
